/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.mattmoore.kotlin.plugins.annotations.example

import kotlin.test.Test

class AppTest {
    @Test fun testAppHasAGreeting() {
    }
}
